name: SquareClans
version: 1.1.8
description: Clan system for spigot 1.12.2
author: ovrays
main: ru.ovrays.squareclans.SquareClansPlugin
softdepend: [Vault,Essentials,PlaceHolderApi]
commands:
  c:
    description: none
  cc:
    description: none
  clan:
    description: none
